import string

password = input("Enter password: ")

def has_punc(c):
    return c in string.punctuation

is_good_len = True if len(password) > 8 else False
has_Upper = any(i.isupper() for i in password)
has_lower = any(i.islower() for i in password)
has_punctuation = any(has_punc(i) for i in password)

if is_good_len and has_lower and has_Upper and has_punctuation:
    print("Strong password")
else:
    print("Weak password")

common_passwords = [
    "123456",
    "password",
    "123456789",
    "12345",
    "12345678",
    "qwerty",
    "abc123",
    "football",
    "monkey",
    "letmein",
    "111111",
    "mustang",
    "access",
    "shadow",
    "master",
    "michael",
    "superman",
    "696969",
    "123123",
    "batman",
    "trustno1",
    "1234567",
    "hello",
    "freedom",
    "whatever",
    "qazwsx",
    "654321",
    "jordan",
    "harley",
    "root",
    "password1",
    "1234",
    "john",
    "fred",
    "merlin",
    "charles",
    "computer",
    "internet",
    "money",
    "phoenix",
    "shadow",
    "princess",
    "panther",
    "solo",
    "happy",
    "home",
    "lakers",
    "yellow",
    "tiger",
    "summer",
    "apple",
    "222222",
    "star",
    "chelsea",
    "winner",
    "amanda",
    "tommy",
    "secret",
    "winner",
    "corvette",
    "alex",
    "andrea",
    "daniel",
    "robert",
    "matthew",
    "joshua",
    "george",
    "andrew",
    "jessica",
    "ashley",
    "1234567890",
    "999999",
    "maggie",
    "cookie",
    "buster",
    "snoopy",
    "ginger",
    "pepper",
    "butter",
    "banana",
    "orange",
    "computer",
    "hockey",
    "soccer",
    "baseball",
    "football",
    "basketball",
    "golf",
    "tennis",
    "pokemon",
    "starwars",
    "superman",
    "batman",
    "spiderman",
    "ironman",
    "wolverine",
    "matrix",
    "admin123",
    "welcome",
    "login",
    "passw0rd",
    "qwerty123",
    "1q2w3e4r",
    "q1w2e3r4",
    "iloveyou",
    "lovely",
    "forever"
]

if password in common_passwords:
    print('Your password was found in commoon passwords.')